# Generated by Django 4.1.5 on 2023-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=380)),
                ('dates', models.DateField()),
                ('location', models.TextField(blank=True, max_length=380)),
            ],
        ),
    ]
